### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by trusktr** [msavin/Fetcher#1]
What's this useful for? Got an example?

**Comment by avalanche1** [comment]
For fetching static data through methods when you don't need a reactive connection.
Otherwise you're going to get a quite pricey server overhead for maintaining reactive subscriptions from thousands of users. Like [here](https://groups.google.com/forum/#!topic/meteor-talk/B_Yi81vRiPA/discussion)

**Comment by trusktr** [comment]
Cool!
