### ISSUE TITLE
Result always undefined

### ISSUE THREAD

**Issue by ralphievolt** [msavin/Fetcher#2]
result is  always get undefined

```
Template.body.onCreated( function() {
   Fetcher.retrieve("taco", "checkIP");
    var res = Fetcher.get("taco");
    console.log(res);
});
```

my methods

```
checkIP: function() {
  return " the boy champ"
}
```

What am I missing?

**Comment by msavin** [comment]
Fetcher.get() is being ran while Fetcher.retrieve() is still executing, so the data is not ready by the time console.log() is ran. A better way to get its value is to run Fetcher.get("taco") in the console.
